### PR TITLE
Enable C++17 testing in circleCI

### PR DESCRIPTION
**Pull request by vissarion**
This PR enables testing in circleCI the C++17 dependent code, following the discussion here: https://github.com/boostorg/geometry/pull/1265#discussion_r1544804957

### CODE REVIEW

**Comment by awulkiew** [comment]
Would it be possible to force b2 to only compile the sources instead of running the tests?
I'm thinking about some mechanism automatically replacing `run` and `link` directive(?) with `compile` for targets in Jamfiles.

**Review by barendgehrels — APPROVED** [review]
Thanks

**Comment by vissarion** [comment]
I have made a try, actually editing Jamfiles. I couldn't find a simpler way; it seems that b2 does not have an only build command. 

An alternative could be to use cmake.

**Comment by vissarion** [comment]
cmake provides a much simpler way to do this (see https://github.com/boostorg/geometry/pull/1302) so I am closing this PR

**Pull request closed without merging**
