### PR TITLE
Example: usage of distance formula

### PR DESCRIPTION
**Pull request by adl1995**
This pull request adds a simple example on how to use a formula (in this case, Karney's direct method).

### CODE REVIEW

**Comment by awulkiew** [comment]
I think this PR should be cleaned up before merging. It seems to add code related to `karney_inverse` formula and strategy which AFAIU was merged recently with additional fixes. It adds many unnecessary merge commits, etc. I thought that GitHub should take it into account and show only the differing parts of the code? Am I missing something?

**Comment by vissarion** [comment]
I agree. I asked Adeel to have a look. It seems that only the last 2
commits are needed.

**Comment by adl1995** [comment]
I just rebased this branch against develop. In fact we only need a single commit in this PR.

**Comment by awulkiew** [comment]
@adl1995 Thanks!

**Pull request merged**
