### PR TITLE
[strategies][cartesian][buffer][join_round] optimize expression

### PR DESCRIPTION
**Pull request by mkaravel**
calculating number of interior points

### CODE REVIEW

**Comment by barendgehrels** [comment]
Looks good - I assume it is unit tested? If so I agree with merging

**Comment by barendgehrels** [comment]
Oh now I relook at it, the std::max should be protected as boost recommends - can you have that too? Otherwise I do it later this week. I'm off now

**Comment by mkaravel** [comment]
`std::max` is now protected (see commit b3b95ae); sorry for that, it slipped.

Yes, unit tests were run, but besides unit tests, you can verify that the two expressions are mathematically equivalent.

**Comment by barendgehrels** [comment]
That's fast! Thanks!

**Pull request merged**
