### PR TITLE
[fix] #750: misspelled config macros

### PR DESCRIPTION
**Pull request by ayaankhan98**
refer to #750

### CODE REVIEW

**Review by vissarion — APPROVED** [review]
Seems OK to me, the macro `BOOST_NO_INT64_T`indicates the absence of `int64_t` and `uint64_t` (as documented in https://www.boost.org/doc/libs/1_74_0/libs/config/doc/html/boost_config/cstdint.html) and the other two (`BOOST_NO_INT64`, `BOOST_HAS_INT64_T`) are not in boost anymore.

**Comment by ayaankhan98** [comment]
@vissarion can you merge this?

**Comment by vissarion** [comment]
> @vissarion can you merge this?

It's a good practice to have at least 2 reviews for each merged PR. @awulkiew @barendgehrels @mloskot any feedback on this PR?

**Comment by awulkiew** [comment]
Yes, I'm ok with merging it. Thanks @ayaankhan98.

Note that all of such checks could be removed because we're moving to the newer standard and 64b int is guaranteed to be available. But let's not do that for now and leave it as it is.

**Review by awulkiew — APPROVED** [review]

**Pull request merged**
