### PR TITLE
Use to_address free function instead of pointer_traits member

### PR DESCRIPTION
**Pull request by glenfe**
The free function was accepted and voted into C++20 (P0653R2).

### CODE REVIEW

**Comment by awulkiew** [comment]
Thanks! I think I'll merge it after 1.66 is released. Is that ok for you?

**Comment by glenfe** [comment]
Yes, no rush. :) Thank you.

**Comment by glenfe** [comment]
The corresponding changes to Boost.Core were merged to its master branch today, so if this change could also be merged to your master, it would be appreciated.

**Comment by awulkiew** [comment]
@glenfe Done.

**Pull request merged**
