### PR TITLE
Allow start for self-turns for difference overlay operations

### PR DESCRIPTION
**Pull request by tinko92**
This changes the handling of colocations in overlay for difference operations such that self-turns are not marked as not startable. As far as I can see, this fixes test case case_recursive_boxes_62 and, I believe, this also solves #900 without breaking any other cases.

Here is a reduced version of that test case, transformed to integer coordinates, in case it needs further analysis:

```cpp
#include <iostream>

#include <boost/geometry.hpp>
#include <boost/geometry/geometries/point_xy.hpp>

namespace bg = boost::geometry;
using point = bg::model::d2::point_xy<int>;
using polygon = bg::model::polygon<point>;
using multi_polygon = bg::model::multi_polygon<polygon>;

int main()
{
    auto a = bg::from_wkt<multi_polygon>("MULTIPOLYGON(((5 3,6 4,5 2,4 4,5 3)),((4 4,4 6,6 4,4 4)),((6 4,6 5,8 4,6 4)),((4 4,2 4,2 5,4 4)))");
    auto b = bg::from_wkt<multi_polygon>("MULTIPOLYGON(((1 1,1 6,9 6,9 1,1 1)))");
    multi_polygon diff;
    bg::difference(b, a, diff);
    std::cout << bg::to_wkt(diff);
    return 0;
}
```

I am not certain that I completely understand the overlay algorithm, though. Is it based on a specific polygon overlay algorithm that can be found in the literature?

With this change applied, I no longer find any error in the set operation results in Boost.Geometry compared to CGAL for any of the test cases, see https://tinko92.github.io/bg_cgal_set_operations_comparison/ (**Edit**: The results on the page are based on the branch in this PR and sorting the column "(BG Real Δ CGAL Real area) / (CGAL Real area)" in descending order shows that there are no examples in which BG and CGAL disagree if both use an infinite-precision number type.) and https://github.com/tinko92/boost-geometry-cgal-set-operation-comparison for the full list and the code used to do the comparison. Maybe the remaining issues (with BOOST_GEOMETRY_TEST_FAILURES)  can be solved with suitable strategies.

### CODE REVIEW

**Comment by barendgehrels** [comment]
Can you add the fixed testcase to the unit testsuite? I checked if (but it's more convenient in this PR):

In file `multi_overlay_cases.hpp`: after `issue_888_53` add :
```
static std::string issue_900[2] =
{
    "MULTIPOLYGON(((5 3,6 4,5 2,4 4,5 3)),((4 4,4 6,6 4,4 4)),((6 4,6 5,8 4,6 4)),((4 4,2 4,2 5,4 4)))",
    "MULTIPOLYGON(((1 1,1 6,9 6,9 1,1 1)))"
};

```

And in difference_multi.cpp, after the same case, add
```
TEST_DIFFERENCE(issue_900, 0, 0.0, 2, 35, 2);
```

Thanks!

**Comment by barendgehrels** [comment]
The algorithm is Graph Traversal and is based on Weiler-Atherton and Greiner–Hormann  (so *not* on Vatti).

So the basic algorithm follows exactly that graph traversal. But things as colocated intersections make it more difficult, those implementations are basically added by myself.

See for example https://www.sciencedirect.com/science/article/pii/S259014861930007X (but I didn't use that article, it didn't exist yet).

**Review by barendgehrels — APPROVED** [review]

**Comment by tinko92** [comment]
Thanks for the link and the feedback. I hope I didn't forget anything in the updated commit. With regard to the comment, out of your suggestions I chose the one of keeping the TODO.

**Review by vissarion — APPROVED** [review]
Looks good! Thanks.

ps. was that a typo?

**Review by awulkiew — APPROVED** [review]

**Comment by barendgehrels** [comment]
> Thanks for the link and the feedback. I hope I didn't forget anything in the updated commit. With regard to the comment, out of your suggestions I chose the one of keeping the TODO.

Looks good, thanks for the testcase, I'll merge it.

**Pull request merged**
