### PR TITLE
Drop dependencies in tests.

### PR DESCRIPTION
**Pull request by awulkiew**
If possible drop type_traits, mpl, typeof, foreach, assign.
Rearrange some includes.

Replacing `MPL_ASSERT` with `static_assert` fixes clang warnings, e.g.:
test\algorithms\comparable_distance.cpp(191,9): warning: unused variable 'mpl_assertion_in_line_203' [-Wunused-variable]

### CODE REVIEW

**Review by vissarion — APPROVED** [review]
Looks OK to me. Thanks.

**Comment by awulkiew** [comment]
I'm considering merging it now and releasing with 1.77. What do you think @barendgehrels @vissarion ?

**Comment by awulkiew** [comment]
@barendgehrels master will be closed for 1.77 on Wed so if possible could you check out this PR and the other 2 latest ones fixing warnings tomorrow?

**Comment by barendgehrels** [comment]
> @barendgehrels master will be closed for 1.77 on Wed so if possible could you review this PR before? If not then I think we'll wait and release it with 1.78 because it's bigger than the simple fixes I already merged.

Sorry I missed this earlier. It's probably too late for 1.77 now anyway. I will approve it.

**Review by barendgehrels — APPROVED** [review]
Thanks

**Comment by awulkiew** [comment]
@barendgehrels Technically changes in tests are allowed even now without permission, but it's quite big so I think I'll wait for 1.78. Thanks!

**Pull request merged**
