### PR TITLE
Fix a missing include for using boost::is_base_of

### PR DESCRIPTION
**Pull request by haubenmi**

### CODE REVIEW

**Review by vissarion — COMMENTED** [review]
Thanks for this fix. Would it be better to use the standard `std::is_base_of` and get ride of the dependency?

**Comment by haubenmi** [comment]
That will probably also work, I will update the pull request accordingly.

**Comment by haubenmi** [comment]
Sorry I need to put this pull request on hold until I get some legal approval from my employer, I hope it can wait until early next week?

**Comment by vissarion** [comment]
> Sorry I need to put this pull request on hold until I get some legal approval from my employer, I hope it can wait until early next week?

Sure, no worries.

**Comment by haubenmi** [comment]
Hi @vissarion, I finally got everything sorted out, pushed a new version that uses std::is_base_of, and posted this PR for review.

**Comment by awulkiew** [comment]
Thanks. Alternatively you could use `bg::util::is_multi<Geometry>::value` from [util/type_traits.hpp](https://github.com/boostorg/geometry/blob/0e961c6ad2f36e34aa71cf716210f4bc3990fd8f/include/boost/geometry/util/type_traits.hpp#L122) but this is fine too.

**Review by awulkiew — APPROVED** [review]

**Review by vissarion — APPROVED** [review]

**Review by barendgehrels — APPROVED** [review]
Thanks!

**Comment by vissarion** [comment]
> I'd also vote for keeping it like this. I just wanted to add that I cannot merge this PR, as I don't have write access, so one of you guys has to do it :)

Sure, I will merge your PR.

**Pull request merged**
