### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### boostorg/geometry now has a Chat Room on Gitter

@mloskot has just created a chat room. You can visit it here: [https://gitter.im/boostorg/geometry](https://gitter.im/boostorg/geometry?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/boostorg/geometry?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by mloskot** [comment]
I have taken the liberty to create the Gitter public room for boostorg/geometry repository.

Apparently, Gitter automatically issues such PR to update README. Whatever we want to do with it...

**Comment by awulkiew** [comment]
Interesting idea.I have nothing against it. I think that there will be small number of people willing to use it but we will never know for sure if we don't try I guess. With that said I'd prefer to place the badge in a different place, in the same time add more badges and change the CI badges to native ones (currently shields.io is used and those badges doesn't work sometimes) like this:
https://github.com/awulkiew/geometry/blob/test/readme/README.md
Are you ok? If the answer was yes, I'd like to close this PR. Would merging this PR trigger something on gitter or could it be safely closed?

**Comment by mloskot** [comment]
On 4 March 2016 at 14:21, Adam Wulkiewicz <notifications@github.com> wrote:

> I think that there will be small number of people willing to use it but we
> will never know for sure if we don't try I guess.
>
And, it does not cost any resource to try.


> With that said I'd prefer to place the badge in a different place, (...)
> Are you ok?
>

Surely, I am.
I will close the PR.

If you need any help with the badges, let me know.

**Comment by awulkiew** [comment]
Readme updated.

**Comment by mloskot** [comment]
Thanks

**Pull request closed without merging**
