### PR TITLE
Add missing headers to precise_math.hpp

### PR DESCRIPTION
**Pull request by tinko92**
I noticed these two missing includes when I tried to use the header on its own.

### CODE REVIEW

**Comment by mloskot** [comment]
@tinko92 Could you try adding `alias ext_triangulation` and see if this catches the missing headers for you? If it does, then this will also serve as re-runnable confirmation of the fix.

https://github.com/boostorg/geometry/blob/6af84a3a4994ac127c5bfe76799e45f0f83d662c/extensions/test/headers/Jamfile#L47-L50

**Comment by tinko92** [comment]
It does. Thanks, I was unaware of this testing facility. It also catches other things that I missed in my tests, I will rebase in a couple of minutes.

**Comment by tinko92** [comment]
The PR now includes the line proposed for the extensions/test/headers/Jamfile and another missing header that was detected through this.

I am not familiar with the other extensions so I am hesitant to open an issue but I noticed that running b2 (in my working copy) in the headers directory produced 17 more failures in total, in extensions_gis, extensions_algorithms and extensions_index. If these are not known false positives, then maybe this is an issue.

**Comment by vissarion** [comment]
First, I am ok with this PR. Regarding failures in extensions I also have 17. I guess they are related to work in progress or outdated code. @barendgehrels @awulkiew should know more.

**Pull request merged**
