### PR TITLE
[readme] update to reflect changes in 1.80

### PR DESCRIPTION
**Pull request by barendgehrels**
I realize it's too late (release is scheduled today), I was earlier confused about release date.
Anyway, I still think it's good to have these changes listed, even though they will be released in 1.81

### CODE REVIEW

**Review by vissarion — APPROVED** [review]
Thanks I agree with the notes!

We could also include 
```* [@https://github.com/boostorg/geometry/pull/1014 1014] Projections: Add new projections and fixes existing ones```

**Comment by awulkiew** [comment]
LGTM, Should I create a separate PR with the changes I've made or should I write them here for you to add now?

**Review by awulkiew — APPROVED** [review]

**Comment by barendgehrels** [comment]
> Thanks I agree with the notes!
> 
> We could also include `* [@https://github.com/boostorg/geometry/pull/1014 1014] Projections: Add new projections and fixes existing ones`

:heavy_check_mark:

**Comment by barendgehrels** [comment]
> LGTM, Should I create a separate PR with the changes I've made or should I write them here for you to add now?

If you could create a separate PR, that would be convenient.

**Pull request merged**
