### PR TITLE
[test][algorithms][buffer] update areas of buffers for some test cases;

### PR DESCRIPTION
**Pull request by mkaravel**
these changes are due to the recent changes in the join_round strategy;

### CODE REVIEW

**Comment by barendgehrels** [comment]
OK - It looks good. If the area is slightly larger, it is usally a bit better (perfectly round has larger area). There are some cases where it is a bit smaller, or the difference is a bit larger. Did you check it visually too?

**Comment by mkaravel** [comment]
No I haven't.

**Comment by barendgehrels** [comment]
I now did for some, it might cause some small bubbles (example in your mailbox)

**Comment by mkaravel** [comment]
Closing this PR and leaving tests as they were.

**Comment by mkaravel** [comment]
See PR #241 reverting the change in the `join_round` strategy.

**Pull request closed without merging**
