### PR TITLE
Add unit test for extensions/test/algorithms/parse.hpp

### PR DESCRIPTION
**Pull request by ayushgupta138**
Second patch for unit test for extensions/test/algorithms/parse.hpp ( #788 ).

### CODE REVIEW

**Comment by ayushgupta138** [comment]
@mloskot  apologies, I could not push to the previous pr #806  due to some conflicts that i couldn't resolve. Please consider this patch for modifications in parse.cpp.

**Comment by mloskot** [comment]
As I mentioned in https://github.com/boostorg/geometry/pull/806#issuecomment-779049596 in the point 4 is that you need to force-push to your branch: `git push --force` and this will overwrite the old branch with the new branch.

**Comment by mloskot** [comment]
@ayushgupta138  By the way, it is a bad idea to submit any contributions from your fork's `develop` branch (like you did here). Instead, always create a topic branch and submit PR from a topic branch. That way, you can easily 'replace' PR branches in your remote without affecting your local develop branch. Topic branches save time!

**Comment by ayushgupta138** [comment]
Thanks for your advice. I will keep that in mind. I have submitted the changes as you said before on the previous pr #806 . Hence, I am closing this pr.

**Pull request closed without merging**
